Comply with standard debhelper maintainer scripts
The old scripts have been upgraded to comply with the debhelper
maintainer script standard.

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -1,10 +1,38 @@
-#!/bin/bash
+#!/bin/sh
 set -e
+# see: dh_installdeb(1)
+#      https://www.debian.org/doc/manuals/maint-guide/dother.en.html#maintscripts
+# summary of how this script can be called:
+#        * <postinst> `configure' <most-recently-configured-version>
+#        * <old-postinst> `abort-upgrade' <new version>
+#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
+#          <new-version>
+#        * <postinst> `abort-remove'
+#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
+#          <failed-install-package> <version> `removing'
+#          <conflicting-package> <version>
+# for details, see https://www.debian.org/doc/debian-policy/ or
+# the debian-policy package
 
-# Habilitando o serviço do maratona-firewall para ser executado no boot do
-# sistema.
-systemctl enable maratona-firewall.service
+case "$1" in
+    configure)
+        # Configure maratona-firewall to start when the system boots up
+        systemctl enable maratona-firewall.service
+        echo "maratona-firewall will take effect after a reboot"
+    ;;
 
-echo "maratona-firewall will take effect after a reboot"
+    abort-upgrade|abort-remove|abort-deconfigure)
+    ;;
+
+    *)
+        echo "postinst called with unknown argument \`$1'" >&2
+        exit 1
+    ;;
+esac
+
+# dh_installdeb will replace this with shell code automatically
+# generated by other debhelper scripts.
+
+#DEBHELPER#
 
 exit 0
